[package]
name = "doing-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }

crossterm = "0.23"
tui = "0.17"

refinery = { version = "0.8", features = ["rusqlite"] }
rusqlite = "0.26"

[[bin]]
name = "dt"
path = "src/main.rs"
